### ISSUE TITLE
Clicking a project title takes one to a "Project Details" page

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/tiger-data-app#262]
Following up from #172, I'd like this to be a "Project Details" page, with "Project Details: " actually included in the page title preceding the project title, as shown in #247

The form is `app/views/projects/show.html.erb`

![Screenshot 2023-12-06 at 11 42 26 AM](https://github.com/pulibrary/tiger-data-app/assets/568286/a6746848-ff93-4852-841e-1bf536175a36)

**Comment by hectorcorrea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tiger-data-app/262?planning-poker) with Zenhub @JaymeeH @jrgriffiniii @leefaisonr

**Comment by JaymeeH** [comment]
@matthewjchandler @hectorcorrea Since there is no Product details page --  as of right now --  I have a "Product Details:" link_text pointing to the Tiger Data homepage. Is that ok for now or should I also setup a boilerplate page for it to link to? Is that necessary since that will be taken care of in issue [#264](https://github.com/pulibrary/tiger-data-app/issues/264) when the page actually gets created -- and we leave a note to comeback and update the link path?

**Comment by hectorcorrea** [comment]
@JaymeeH The project show page (https://github.com/pulibrary/tiger-data-app/blob/main/app/views/projects/show.html.erb) is the "Product Details"

**Comment by matthewjchandler** [comment]
My concern was mainly about the title that displays on the page for the user. It should be "Project Details: [insert project title]". I believe you all have been calling this the "show" page, where the project details are shown, but I've been calling it the "Project Details" page in my design materials

**Comment by matthewjchandler** [comment]
@JaymeeH Yes, I don't have a need for a link out to a different page in this issue. It's really just about the page title displayed for the user
